### ISSUE TITLE
RebindingBC Bug

### ISSUE THREAD

**Issue by dixonth1silicon** [ADicksonLab/wepy#25] opened 2021-05-20 21:25 UTC
Line 480 in receptor.py needs to be changed from:

```
        super().__init__(initial_states=initial_states,
                                 initial_weights=initial_weights,
                                 ligand_idxs=ligand_idxs,
                                 receptor_idxs=binding_site_idx
                                 **kwargs)

```

to 

        super().__init__(initial_states=initial_states,
                                 initial_weights=initial_weights
                                 ligand_idxs=ligand_idxs,
                                 receptor_idxs=binding_site_idxs,
                                 **kwargs)

**Comment by salotz-sitx** [comment] 2021-05-20 21:47
Duplicate of #17

**Closed by salotz-sitx** 2021-05-20 21:47 UTC
